### ISSUE TITLE
“Online” Links to Buttons 

### ISSUE THREAD

**Issue by anaister** [popUpZendo/popUpZendo#14]
Consider changing the hyperlinked word “Online” under the home page event listings to a button so it’s more obviously a link to the zoom meeting.

**Comment by bennmeyers** [comment]
I did what I could: I made sure links were present and added a button, but I couldn't change the text to  an inline button

**Comment by anaister** [comment]
Hey there, 

Maybe we should meet on zoom to draw out design concepts for the web, because I realize how easy it is to miscommunicate by email. Sorry for the confusion, but I actually meant to ask for buttons on the home page, not the individual event pages. I added the buttons on the home page based on what I think Joe was asking for. 

But since I saw that you made edits to the event listing, I decided to take a closer look. I made some additional edits to the Practical Zen listing for the next two weeks to be super clear it was online. This came up because someone from Meetup messaged and was confused wondering if we were meeting in person. So I want it to be abundantly clear we are meeting online. To that end I removed the map in the event listing, I changed the location to “online” in both the summary content and page content and put a link directly to the zoom room. (I only did this for the events coming up in the next two weeks.) Can we replicate this look and content for Midday through April 7th when the shelter in order may be lifted?

Also it occurs to me that we should remove the zoom link in the “persistent” event at the top because that link goes to a different room than the meeting locations for Midday or Practical Zen. (Note that the two meetings have different link IDs.) 

I hope I’m not stepping on your toes by doing that work. I just thought it might take longer to try and communicate it all by email. Hope that all makes sense. Let me know if you have any questions or concerns with me editing to the website.

Thanks,
Anais

**Comment by bennmeyers** [comment]
I added a link to the zoom event to the Location in the options area

**Comment by bennmeyers** [comment]
The Persistent event was changed

**Comment by bennmeyers** [comment]
This should be complete at this point
